/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
 //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
 
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};
module.exports = {
  someSidebar: {
    '플러그인': ['GPT/HanmiGPT','GPT/DocsGPT','GPT/VoiceGPT','GPT/Google'],
    
  },
  someSidebar2: { 
    'Support': ['FAQ/자주 묻는 질문']
  },
  someSidebar3: { 
    '소개': ['intro/index','intro/hanmigpt']
  },
};
